In [70]:
#build for series and dataframe
#panel data - padas
#build on numpy

In [71]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [72]:
import numpy as np
import pandas as pd

In [73]:
#series - only one column and multiple rows

In [74]:
data = [10,20,30,40,50,60]  # list

In [75]:
data

[10, 20, 30, 40, 50, 60]

In [76]:
pd.Series(data)

0    10
1    20
2    30
3    40
4    50
5    60
dtype: int64

In [77]:
pd.Series(data , index =["a", "b", "c", "d", "e", "f"])

a    10
b    20
c    30
d    40
e    50
f    60
dtype: int64

In [78]:
#dict

In [79]:
data = {"a":10, "b":20, "c":30}

In [80]:
pd.Series(data)

a    10
b    20
c    30
dtype: int64

In [81]:
pd.Series(data, name= "Column1")

a    10
b    20
c    30
Name: Column1, dtype: int64

In [82]:
data1 = { "name": ["rahul", "shubham", "sneha"],
         "Age": [28,27,30],
          "city": ["wardha", "pune", "yavatmal"]}

In [83]:
data1

{'name': ['rahul', 'shubham', 'sneha'],
 'Age': [28, 27, 30],
 'city': ['wardha', 'pune', 'yavatmal']}

In [84]:
# series

In [85]:
pd.Series(data1, name="column1")

name     [rahul, shubham, sneha]
Age                 [28, 27, 30]
city    [wardha, pune, yavatmal]
Name: column1, dtype: object

In [86]:
#dataframe

In [87]:
pd.DataFrame(data1)

      name  Age      city
0    rahul   28    wardha
1  shubham   27      pune
2    sneha   30  yavatmal

In [88]:
pd.DataFrame(data1, index=["row1", "row2", "row3"])

         name  Age      city
row1    rahul   28    wardha
row2  shubham   27      pune
row3    sneha   30  yavatmal

In [89]:
df = pd.DataFrame(data1, index=["row1", "row2", "row3"])

In [90]:
df

         name  Age      city
row1    rahul   28    wardha
row2  shubham   27      pune
row3    sneha   30  yavatmal

In [91]:
# attribute

In [92]:
df.index

Index(['row1', 'row2', 'row3'], dtype='object')

In [93]:
df.columns

Index(['name', 'Age', 'city'], dtype='object')

In [94]:
df.dtypes

name    object
Age      int64
city    object
dtype: object

In [95]:
df.shape

(3, 3)

In [96]:
df.ndim

2

In [97]:
df.size

9

In [98]:
df.values

array([['rahul', 28, 'wardha'],
       ['shubham', 27, 'pune'],
       ['sneha', 30, 'yavatmal']], dtype=object)

In [99]:
# methods

In [100]:
df.head()   #always shows first 5 rows

         name  Age      city
row1    rahul   28    wardha
row2  shubham   27      pune
row3    sneha   30  yavatmal

In [101]:
df.head(2)

         name  Age    city
row1    rahul   28  wardha
row2  shubham   27    pune

In [102]:
df.tail() #last 5 rows

         name  Age      city
row1    rahul   28    wardha
row2  shubham   27      pune
row3    sneha   30  yavatmal

In [103]:
df.tail(1)

       name  Age      city
row3  sneha   30  yavatmal

In [104]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, row1 to row3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   Age     3 non-null      int64
 2   city    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

In [105]:
df.describe()

             Age
count   3.000000
mean   28.333333
std     1.527525
min    27.000000
25%    27.500000
50%    28.000000
75%    29.000000
max    30.000000

In [106]:
df.describe(include="all")

         name        Age    city
count       3   3.000000       3
unique      3        NaN       3
top     rahul        NaN  wardha
freq        1        NaN       1
mean      NaN  28.333333     NaN
std       NaN   1.527525     NaN
min       NaN  27.000000     NaN
25%       NaN  27.500000     NaN
50%       NaN  28.000000     NaN
75%       NaN  29.000000     NaN
max       NaN  30.000000     NaN

In [107]:
df.sample(2)

         name  Age      city
row2  shubham   27      pune
row3    sneha   30  yavatmal

In [108]:
#pandas read function

In [109]:
#excel -worksheet
#csv - comma sepreted values
#jeson

In [110]:
#pd.read

In [111]:
df = pd.read_csv("/content/sample_data/california_housing_test.csv")

In [112]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [113]:
df.sample(2)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
1708,-120.88,38.45,25.0,1374.0,297.0,657.0,288.0,2.5476,97900.0
1385,-122.42,37.71,44.0,2080.0,489.0,1781.0,478.0,3.6827,215300.0

In [114]:
df["total_rooms"]

0       3885.0
1       1510.0
2       3589.0
3         67.0
4       1241.0
         ...
2995    1450.0
2996    5257.0
2997     956.0
2998      96.0
2999    1765.0
Name: total_rooms, Length: 3000, dtype: float64

In [115]:
df[["total_rooms", "total_bedrooms"]]

      total_rooms  total_bedrooms
0          3885.0           661.0
1          1510.0           310.0
2          3589.0           507.0
3            67.0            15.0
4          1241.0           244.0
...           ...             ...
2995       1450.0           642.0
2996       5257.0          1082.0
2997        956.0           201.0
2998         96.0            14.0
2999       1765.0           263.0

[3000 rows x 2 columns]

In [116]:
df.iloc[2997]   #index location

longitude              -119.7000
latitude                 36.3000
housing_median_age       10.0000
total_rooms             956.0000
total_bedrooms          201.0000
population              693.0000
households              220.0000
median_income             2.2895
median_house_value    62000.0000
Name: 2997, dtype: float64

In [117]:
df1 = pd.DataFrame(data1, index=["row1", "row2", "row3"])

In [118]:
df1

         name  Age      city
row1    rahul   28    wardha
row2  shubham   27      pune
row3    sneha   30  yavatmal

In [119]:
df1.iloc[1]  #number

name    shubham
Age          27
city       pune
Name: row2, dtype: object

In [120]:
df1.loc['row1']  #name

name     rahul
Age         28
city    wardha
Name: row1, dtype: object

In [121]:
import numpy as np
import pandas as pd

In [122]:
df = pd.read_csv ("/content/sample_data/california_housing_test.csv")

In [123]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0

In [124]:
df['longitude']

0      -122.05
1      -118.30
2      -117.81
3      -118.36
4      -119.67
         ...
2995   -119.86
2996   -118.14
2997   -119.70
2998   -117.12
2999   -119.63
Name: longitude, Length: 3000, dtype: float64

In [125]:
df['housing_median_age'].describe()

count    3000.000000
mean       28.845333
std        12.555396
min         1.000000
25%        18.000000
50%        29.000000
75%        37.000000
max        52.000000
Name: housing_median_age, dtype: float64

In [126]:
df[df['housing_median_age'] < 2]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
842,-117.95,35.08,1.0,83.0,15.0,32.0,15.0,4.875,141700.0
1115,-116.95,33.86,1.0,6.0,2.0,8.0,2.0,1.625,55000.0

In [127]:
df[df['housing_median_age'] < 2]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
842,-117.95,35.08,1.0,83.0,15.0,32.0,15.0,4.875,141700.0
1115,-116.95,33.86,1.0,6.0,2.0,8.0,2.0,1.625,55000.0

In [128]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [129]:
df.sort_values("housing_median_age")

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
842,-117.95,35.08,1.0,83.0,15.0,32.0,15.0,4.8750,141700.0
1115,-116.95,33.86,1.0,6.0,2.0,8.0,2.0,1.6250,55000.0
2452,-117.64,33.87,2.0,17470.0,2727.0,5964.0,1985.0,6.2308,257900.0
2429,-117.20,33.58,2.0,30450.0,5033.0,9419.0,3197.0,4.5936,174300.0
1050,-121.96,37.74,2.0,200.0,20.0,25.0,9.0,15.0001,350000.0
...,...,...,...,...,...,...,...,...,...
26,-122.42,37.76,52.0,3587.0,1030.0,2259.0,979.0,2.5403,250000.0
36,-122.53,37.97,52.0,1560.0,451.0,700.0,419.0,2.5125,270800.0
2965,-122.44,37.71,52.0,2711.0,591.0,1848.0,524.0,3.9567,251500.0
2970,-122.47,37.77,52.0,2241.0,443.0,1042.0,377.0,4.1635,398400.0
2972,-118.14,34.17,52.0,2667.0,486.0,1681.0,504.0,4.0524,173100.0

In [130]:
df.sort_values("housing_median_age").reset_index()

,index,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,842,-117.95,35.08,1.0,83.0,15.0,32.0,15.0,4.8750,141700.0
1,1115,-116.95,33.86,1.0,6.0,2.0,8.0,2.0,1.6250,55000.0
2,2452,-117.64,33.87,2.0,17470.0,2727.0,5964.0,1985.0,6.2308,257900.0
3,2429,-117.20,33.58,2.0,30450.0,5033.0,9419.0,3197.0,4.5936,174300.0
4,1050,-121.96,37.74,2.0,200.0,20.0,25.0,9.0,15.0001,350000.0
...,...,...,...,...,...,...,...,...,...,...
2995,26,-122.42,37.76,52.0,3587.0,1030.0,2259.0,979.0,2.5403,250000.0
2996,36,-122.53,37.97,52.0,1560.0,451.0,700.0,419.0,2.5125,270800.0
2997,2965,-122.44,37.71,52.0,2711.0,591.0,1848.0,524.0,3.9567,251500.0
2998,2970,-122.47,37.77,52.0,2241.0,443.0,1042.0,377.0,4.1635,398400.0
2999,2972,-118.14,34.17,52.0,2667.0,486.0,1681.0,504.0,4.0524,173100.0

In [131]:
df["New_Age"] = df['housing_median_age']*2

In [132]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,New_Age
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0,54.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0,86.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0,54.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0,56.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0,38.0
...,...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0,46.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0,54.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0,20.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0,80.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0,84.0

In [133]:
df.drop("longitude", axis= 1)

,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,New_Age
0,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0,54.0
1,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0,86.0
2,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0,54.0
3,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0,56.0
4,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0,38.0
...,...,...,...,...,...,...,...,...,...
2995,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0,46.0
2996,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0,54.0
2997,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0,20.0
2998,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0,80.0
2999,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0,84.0

In [134]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,New_Age
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0,54.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0,86.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0,54.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0,56.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0,38.0
...,...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0,46.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0,54.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0,20.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0,80.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0,84.0

In [135]:
df.drop('longitude', axis=1 , inplace=True)
#inplace = Trye for permenent delete

In [136]:
df.head()

,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,New_Age
0,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0,54.0
1,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0,86.0
2,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0,54.0
3,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0,56.0
4,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0,38.0

In [137]:
df.rename(columns={"latitude" :"location"})

,location,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,New_Age
0,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0,54.0
1,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0,86.0
2,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0,54.0
3,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0,56.0
4,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0,38.0
...,...,...,...,...,...,...,...,...,...
2995,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0,46.0
2996,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0,54.0
2997,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0,20.0
2998,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0,80.0
2999,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0,84.0

In [138]:
# null values -missing values

In [139]:
df.isnull()

,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,New_Age
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
2995,False,False,False,False,False,False,False,False,False
2996,False,False,False,False,False,False,False,False,False
2997,False,False,False,False,False,False,False,False,False
2998,False,False,False,False,False,False,False,False,False
2999,False,False,False,False,False,False,False,False,False

In [140]:
df.isnull().sum()

latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
New_Age               0
dtype: int64

In [141]:
df.notnull().sum()

latitude              3000
housing_median_age    3000
total_rooms           3000
total_bedrooms        3000
population            3000
households            3000
median_income         3000
median_house_value    3000
New_Age               3000
dtype: int64

In [142]:
# fill the null values

df.fillna("Tushar")

,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,New_Age
0,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0,54.0
1,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0,86.0
2,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0,54.0
3,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0,56.0
4,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0,38.0
...,...,...,...,...,...,...,...,...,...
2995,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0,46.0
2996,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0,54.0
2997,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0,20.0
2998,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0,80.0
2999,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0,84.0

In [143]:
# delete null values
df.dropna(inplace=True)

In [144]:
#aggregation

In [145]:
df['total_rooms'].sum()

np.float64(7798736.0)

In [146]:
df["total_rooms"].mean()

np.float64(2599.578666666667)

In [147]:
df['total_rooms'].median()

2106.0

In [148]:
df['total_rooms'].mode()

0     907.0
1    1778.0
2    1787.0
3    1966.0
Name: total_rooms, dtype: float64

In [149]:
df["total_rooms"].min()

6.0

In [150]:
df['total_rooms'].max()

30450.0

In [152]:
df['total_rooms'].value_counts().sort_index()

total_rooms
6.0        1
16.0       1
18.0       1
19.0       1
21.0       1
          ..
21988.0    1
23915.0    1
24121.0    1
27870.0    1
30450.0    1
Name: count, Length: 2215, dtype: int64

In [153]:
import seaborn as sns
df = sns.load_dataset("titanic")

In [154]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [155]:
df.shape

(891, 15)

In [156]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [158]:
df['sex'].value_counts()

sex
male      577
female    314
Name: count, dtype: int64

In [160]:
df.groupby("sex")['survived'].mean()*100

sex
female    74.203822
male      18.890815
Name: survived, dtype: float64

In [161]:
df.groupby(["sex", "pclass"])['survived'].mean()*100

sex     pclass
female  1         96.808511
        2         92.105263
        3         50.000000
male    1         36.885246
        2         15.740741
        3         13.544669
Name: survived, dtype: float64

In [162]:
df.groupby(["sex", "pclass"])['survived'].mean().unstack()

pclass         1         2         3
sex
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [163]:
df['age'].unique()

array([22.  , 38.  , 26.  , 35.  ,   nan, 54.  ,  2.  , 27.  , 14.  ,
        4.  , 58.  , 20.  , 39.  , 55.  , 31.  , 34.  , 15.  , 28.  ,
        8.  , 19.  , 40.  , 66.  , 42.  , 21.  , 18.  ,  3.  ,  7.  ,
       49.  , 29.  , 65.  , 28.5 ,  5.  , 11.  , 45.  , 17.  , 32.  ,
       16.  , 25.  ,  0.83, 30.  , 33.  , 23.  , 24.  , 46.  , 59.  ,
       71.  , 37.  , 47.  , 14.5 , 70.5 , 32.5 , 12.  ,  9.  , 36.5 ,
       51.  , 55.5 , 40.5 , 44.  ,  1.  , 61.  , 56.  , 50.  , 36.  ,
       45.5 , 20.5 , 62.  , 41.  , 52.  , 63.  , 23.5 ,  0.92, 43.  ,
       60.  , 10.  , 64.  , 13.  , 48.  ,  0.75, 53.  , 57.  , 80.  ,
       70.  , 24.5 ,  6.  ,  0.67, 30.5 ,  0.42, 34.5 , 74.  ])

In [164]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64